# Generated by Django 6.0.5 on 2026-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='description',
        ),
        migrations.AlterField(
            model_name='bug',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
